host_inventory_url: http://inventory-web:8081
remediations_url: https://ci.cloud.redhat.com
rbac_url: https://ci.cloud.redhat.com
# disable_rbac: true
# platform_basic_auth_username: myusername
# platform_basic_auth_password: secret
prometheus_exporter_host: prometheus
prometheus_exporter_port: 9394
redis_url: localhost:6379
redis_cache_url: localhost:6379
